//
// Created by Artem Novikov on 17.02.2023.
//

#ifndef FERMIBREAKUP_MYFERMIBREAKUP_FRAGMENTS_FRAGMENTTABLE_H_
#define FERMIBREAKUP_MYFERMIBREAKUP_FRAGMENTS_FRAGMENTTABLE_H_

class FragmentTable {

};

#endif //FERMIBREAKUP_MYFERMIBREAKUP_FRAGMENTS_FRAGMENTTABLE_H_
